name: beszel-agent

services:
  beszel-agent-service:
    image: henrygd/beszel-agent:${BESZEL_VERSION}
    container_name: beszel-agent-service
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LISTEN=45876
      - KEY=${BESZEL_KEY}
      - HUB_URL=${BESZEL_HUB_URL}
      - TOKEN=${BESZEL_TOKEN}
    network_mode: host
    restart: unless-stopped

volumes:
  beszel_agent_data:
